version: '3'
services:
  app_server:
    container_name: app-server
    build: ./app-server
    environment:
      - FLASK_APP=/srv/app/wsgi.py
      - FLASK_DEBUG=1
      - FLASK_SECRET_KEY=sandbox
      - DB_USER=sandbox
      - DB_PASSWORD=sandbox
      - DB_NAME=sandbox
      - DB_HOST=database:5432
    ports:
      - "5000:5000"
    volumes:
      - ./app-server/app:/srv/app
    command: flask run --host=0.0.0.0 --port=5000

  database:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_USER=sandbox
      - POSTGRES_DB=sandbox
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
